// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ClientProfileRule.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RegulationRuleModel
    {
        /// <summary>
        /// Initializes a new instance of the RegulationRuleModel class.
        /// </summary>
        public RegulationRuleModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RegulationRuleModel class.
        /// </summary>
        public RegulationRuleModel(string regulationId = default(string), string profileId = default(string))
        {
            RegulationId = regulationId;
            ProfileId = profileId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RegulationId")]
        public string RegulationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProfileId")]
        public string ProfileId { get; set; }

    }
}
